package gojxl

import (
	"os"
	"path/filepath"
	"testing"
)

// expectedSample returns the original sample value for fixture pixel index i
// (row-major) and channel c, matching how the fixtures were generated by cjxl
// from synthetic PNM input (see the generation in the project history).
func gray8Ramp() []int32 {
	return []int32{
		0x00, 0x20, 0x40, 0x60, 0x80, 0xA0, 0xC0, 0xE0,
		0x10, 0x30, 0x50, 0x70, 0x90, 0xB0, 0xD0, 0xF0,
		0x08, 0x18, 0x28, 0x38, 0x48, 0x58, 0x68, 0x78,
		0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
	}
}

// TestModularDecodeFixtures decodes every lossless Modular fixture end-to-end
// (container/headers → frame → MA tree → predictors → inverse RCT) and verifies
// the channels byte-exact against the original images.
func TestModularDecodeFixtures(t *testing.T) {
	cases := []struct {
		file     string
		w, h     int
		channels int
		expect   func(i, c int) int32
	}{
		{"gray8_8x4_lossless.jxl", 8, 4, 1, func(i, c int) int32 { return gray8Ramp()[i] }},
		{"gray16_8x4_lossless.jxl", 8, 4, 1, func(i, c int) int32 { return int32((i * 1000) & 0xFFFF) }},
		{"rgb8_8x4_lossless.jxl", 8, 4, 3, func(i, c int) int32 { return int32((i*3 + c*40) & 0xFF) }},
		{"rgb16_6x6_lossless.jxl", 6, 6, 3, func(i, c int) int32 { return int32((i*700 + c*5000) & 0xFFFF) }},
		{"rgba8_8x4_lossless.jxl", 8, 4, 4, func(i, c int) int32 { return int32((i*2 + c*30) & 0xFF) }},
		{"gray8_300x200_lossless.jxl", 300, 200, 1, func(i, c int) int32 {
			return int32(((i % 300) + (i / 300)) & 0xFF)
		}},
		// photo: big multi-node tree, no transform.
		{"photo_e7.jxl", 64, 48, 1, func(i, c int) int32 {
			x, y := i%64, i/64
			return int32((x*2 + y*3 + (x*y)/16 + (x ^ y)) & 0xFF)
		}},
		// responsive: Squeeze transform.
		{"sq_resp.jxl", 64, 48, 1, func(i, c int) int32 {
			x, y := i%64, i/64
			return int32((x*2 + y*3 + (x*y)/16 + (x ^ y)) & 0xFF)
		}},
		// palette: Palette transform (4 colors).
		{"pal_e7.jxl", 32, 32, 3, func(i, c int) int32 {
			x, y := i%32, i/32
			pal := [4][3]int32{{10, 20, 30}, {200, 100, 50}, {0, 0, 0}, {255, 255, 255}}
			return pal[(x/8+y/8)%4][c]
		}},
		// multi-group grayscale (1500x48 → 6 groups).
		{"wide_e7.jxl", 1500, 48, 1, func(i, c int) int32 {
			x, y := i%1500, i/1500
			return int32((x + y*5 + (x*y)/64) & 0xFF)
		}},
		// multi-group RGB with per-group RCT (1300x40).
		{"wrgb_e7.jxl", 1300, 40, 3, func(i, c int) int32 {
			x, y := i%1300, i/1300
			switch c {
			case 0:
				return int32((x + y) & 0xFF)
			case 1:
				return int32((x*2 + y) & 0xFF)
			default:
				return int32((x + y*3) & 0xFF)
			}
		}},
		// large multi-group RGB (1200x800, 2.88M samples).
		{"r_bigcolor.jxl", 1200, 800, 3, func(i, c int) int32 {
			x, y := i%1200, i/1200
			switch c {
			case 0:
				return int32((x + y) & 0xFF)
			case 1:
				return int32((x*2 + y) & 0xFF)
			default:
				return int32((x + y*3) & 0xFF)
			}
		}},
		// large multi-group 16-bit grayscale (1100x900).
		{"r_big16.jxl", 1100, 900, 1, func(i, c int) int32 {
			x, y := i%1100, i/1100
			return int32((x*7 + y*13) & 0xFFFF)
		}},
	}
	for _, c := range cases {
		t.Run(c.file, func(t *testing.T) {
			data, err := os.ReadFile(filepath.Join("testdata", c.file))
			if err != nil {
				t.Skipf("fixture unavailable: %v", err)
			}
			image, _, err := decodeModularFrame(data)
			if err != nil {
				t.Fatalf("decode: %v", err)
			}
			if len(image) != c.channels {
				t.Fatalf("channels: got %d want %d", len(image), c.channels)
			}
			n := c.w * c.h
			mism := 0
			for ch := 0; ch < c.channels; ch++ {
				for i := 0; i < n; i++ {
					if image[ch].pix[i] != c.expect(i, ch) {
						if mism < 5 {
							t.Errorf("ch %d px %d: got %d want %d", ch, i, image[ch].pix[i], c.expect(i, ch))
						}
						mism++
					}
				}
			}
			if mism > 0 {
				t.Fatalf("%d/%d samples mismatch", mism, n*c.channels)
			}
		})
	}
}
