package gojxl

import (
	"os"
	"path/filepath"
	"testing"
)

// expectedSample returns the original sample value for fixture pixel index i
// (row-major) and channel c, matching how the fixtures were generated by cjxl
// from synthetic PNM input (see the generation in the project history).
func gray8Ramp() []int32 {
	return []int32{
		0x00, 0x20, 0x40, 0x60, 0x80, 0xA0, 0xC0, 0xE0,
		0x10, 0x30, 0x50, 0x70, 0x90, 0xB0, 0xD0, 0xF0,
		0x08, 0x18, 0x28, 0x38, 0x48, 0x58, 0x68, 0x78,
		0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
	}
}

// TestModularDecodeFixtures decodes every lossless Modular fixture end-to-end
// (container/headers → frame → MA tree → predictors → inverse RCT) and verifies
// the channels byte-exact against the original images.
func TestModularDecodeFixtures(t *testing.T) {
	cases := []struct {
		file     string
		w, h     int
		channels int
		expect   func(i, c int) int32
	}{
		{"gray8_8x4_lossless.jxl", 8, 4, 1, func(i, c int) int32 { return gray8Ramp()[i] }},
		{"gray16_8x4_lossless.jxl", 8, 4, 1, func(i, c int) int32 { return int32((i * 1000) & 0xFFFF) }},
		{"rgb8_8x4_lossless.jxl", 8, 4, 3, func(i, c int) int32 { return int32((i*3 + c*40) & 0xFF) }},
		{"rgb16_6x6_lossless.jxl", 6, 6, 3, func(i, c int) int32 { return int32((i*700 + c*5000) & 0xFFFF) }},
		{"rgba8_8x4_lossless.jxl", 8, 4, 4, func(i, c int) int32 { return int32((i*2 + c*30) & 0xFF) }},
		{"gray8_300x200_lossless.jxl", 300, 200, 1, func(i, c int) int32 {
			return int32(((i % 300) + (i / 300)) & 0xFF)
		}},
	}
	for _, c := range cases {
		t.Run(c.file, func(t *testing.T) {
			data, err := os.ReadFile(filepath.Join("testdata", c.file))
			if err != nil {
				t.Fatal(err)
			}
			image, _, err := decodeModularFrame(data)
			if err != nil {
				t.Fatalf("decode: %v", err)
			}
			if len(image) != c.channels {
				t.Fatalf("channels: got %d want %d", len(image), c.channels)
			}
			n := c.w * c.h
			mism := 0
			for ch := 0; ch < c.channels; ch++ {
				for i := 0; i < n; i++ {
					if image[ch].pix[i] != c.expect(i, ch) {
						if mism < 5 {
							t.Errorf("ch %d px %d: got %d want %d", ch, i, image[ch].pix[i], c.expect(i, ch))
						}
						mism++
					}
				}
			}
			if mism > 0 {
				t.Fatalf("%d/%d samples mismatch", mism, n*c.channels)
			}
		})
	}
}
